### ISSUE TITLE
Input with sensor address 1 is ignored

### ISSUE THREAD

**Issue by cbovy** [ClubNCaldes/SVLocoIO#3]
I've configured the  GCA50an for 16 inputs, but the input which is connected to sensor address 1 is ignored.
I believe it is because of the following line:

```
--- SVLocoIO-old.ino	2020-12-29 21:13:46.997911309 +0100
+++ SVLocoIO-new.ino	2020-12-29 21:15:04.710904824 +0100
@@ -207,7 +207,7 @@
   // Check inputs to inform 
   for (n=0; n<16; n++)
   {
-    if (!bitRead(svtable.svt.pincfg[n].cnfg,7) && myAddr[n]>1)   //Setup as an Input greater than 1
+    if (!bitRead(svtable.svt.pincfg[n].cnfg,7) && myAddr[n]>=1)   //Setup as an Input greater than 1
     {
       //Check if state changed 
       currentState=digitalRead(pinMap[n]);
```

Can you verify?
Thanks!

Regards, Charles

**Comment by cbovy** [comment]
I've created a pull-request: https://github.com/ClubNCaldes/SVLocoIO/pull/4

**Comment by ClubNCaldes** [comment]
Be careful using addresses under 5, some command statios use them to inform about its state.
